# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.bank_api:
        class:  AppBundle\Service\BankApi

    app.currency_service:
        class:  AppBundle\Service\CurrencyService
        arguments: ["@doctrine.orm.entity_manager"]

    app.form.tax:
        class:  AppBundle\Form\TaxType
        arguments: ["@app.currency_service"]