version: "3.1"
services:
  nginx:
    image: nginx:latest
    environment:
      - VIRTUAL_HOST=currency.local
    ports:
      - 7779:80
    links:
      - php
    volumes:
      - ../:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: currency_nginx
  php:
    build: ./php/
    expose:
      - 9000
    links:
      - db
    volumes:
      - ../:/var/www/html:cached
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    container_name: currency_php

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
     - 7777:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080