version: "3.1"
services:
  nginx:
    image: nginx:latest
    ports:
      - 7779:80
    links:
      - php
    volumes:
      - ../:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: currency_nginx
  php:
    build: ./php/
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - ../:/var/www/html:cached
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    container_name: currency_php

  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: currency
      MYSQL_USER: currency
      MYSQL_PASSWORD: currency
    ports:
     - 7777:3306
    container_name: currency_db