version: "3.1"
services:
  nginx:
    image: nginx:latest
    ports:
      - 7777:80
    links:
      - php
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: currency_nginx
  php:
    build: ./php/
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - ../:/var/www/html
    container_name: currency_php
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: currency
      MYSQL_USER: currency
      MYSQL_PASSWORD: currency
    container_name: currency_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 7778:80
    volumes:
     - /sessions